import { useState, useEffect } from 'react';
import axiosInstance from '../api/axiosInstance';
import PageWrapper from '../components/layout/PageWrapper';
import { FileText, Download, Plus, RefreshCw } from 'lucide-react';
import { toast } from 'react-toastify';

function Reports() {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);

  const fetchReports = async () => {
    try {
      setLoading(true);
      const res = await axiosInstance.get('/api/reports');
      setReports(res.data.data || []);
    } catch (err) {
      toast.error('Failed to fetch reports');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchReports();
  }, []);

  const generateReport = async () => {
    try {
      setGenerating(true);
      await axiosInstance.post('/api/reports/generate', {});
      toast.success('Report generated successfully!');
      fetchReports();
    } catch (err) {
      toast.error(err.response?.data?.message || 'Failed to generate report');
    } finally {
      setGenerating(false);
    }
  };

  const downloadReport = async (id) => {
    try {
      const response = await axiosInstance.get(
        `/api/reports/${id}/download`,
        { responseType: 'blob' }
      );
      const url = window.URL.createObjectURL(new Blob([response.data]));
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', `report-${id}.pdf`);
      document.body.appendChild(link);
      link.click();
      link.remove();
      toast.success('Report downloaded!');
    } catch (err) {
      toast.error('Download failed');
    }
  };

  return (
    <PageWrapper>
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-2xl font-bold text-white flex items-center gap-2">
            <FileText className="w-7 h-7 text-blue-400" />
            Forensic Reports
          </h1>
          <p className="text-gray-400 text-sm mt-1">
            Generate and download PDF investigation reports
          </p>
        </div>
        <div className="flex gap-2">
          <button
            onClick={fetchReports}
            className="btn-secondary flex items-center gap-2"
          >
            <RefreshCw className="w-4 h-4" />
            Refresh
          </button>
          <button
            onClick={generateReport}
            disabled={generating}
            className="btn-primary flex items-center gap-2"
          >
            <Plus className="w-4 h-4" />
            {generating ? 'Generating...' : 'Generate Report'}
          </button>
        </div>
      </div>

      {/* Reports List */}
      <div className="card p-0 overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead className="bg-gray-700">
              <tr>
                <th className="text-left px-4 py-3 text-xs text-gray-400 font-medium">Report Title</th>
                <th className="text-left px-4 py-3 text-xs text-gray-400 font-medium">Generated By</th>
                <th className="text-left px-4 py-3 text-xs text-gray-400 font-medium">Cases</th>
                <th className="text-left px-4 py-3 text-xs text-gray-400 font-medium">Alerts</th>
                <th className="text-left px-4 py-3 text-xs text-gray-400 font-medium">Status</th>
                <th className="text-left px-4 py-3 text-xs text-gray-400 font-medium">Date</th>
                <th className="text-left px-4 py-3 text-xs text-gray-400 font-medium">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-700">
              {loading ? (
                <tr>
                  <td colSpan={7} className="px-4 py-8 text-center text-gray-400">
                    Loading reports...
                  </td>
                </tr>
              ) : reports.length === 0 ? (
                <tr>
                  <td colSpan={7} className="px-4 py-8 text-center">
                    <FileText className="w-10 h-10 text-gray-600 mx-auto mb-2" />
                    <p className="text-gray-400">No reports yet. Click Generate Report!</p>
                  </td>
                </tr>
              ) : (
                reports.map((report) => (
                  <tr key={report._id} className="hover:bg-gray-700/50 transition-colors">
                    <td className="px-4 py-3">
                      <p className="text-sm text-white font-medium">{report.title}</p>
                    </td>
                    <td className="px-4 py-3 text-sm text-gray-300">
                      {report.generatedBy?.name || 'Unknown'}
                    </td>
                    <td className="px-4 py-3 text-sm text-gray-300">
                      {report.summary?.totalCases || 0}
                    </td>
                    <td className="px-4 py-3 text-sm text-gray-300">
                      {report.summary?.totalAlerts || 0}
                    </td>
                    <td className="px-4 py-3">
                      <span className={`inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium ${
                        report.status === 'ready'
                          ? 'bg-green-900 text-green-200'
                          : report.status === 'generating'
                          ? 'bg-yellow-900 text-yellow-200'
                          : 'bg-red-900 text-red-200'
                      }`}>
                        {report.status}
                      </span>
                    </td>
                    <td className="px-4 py-3 text-sm text-gray-400">
                      {new Date(report.createdAt).toLocaleDateString()}
                    </td>
                    <td className="px-4 py-3">
                      <button
                        onClick={() => downloadReport(report._id)}
                        className="flex items-center gap-1 text-blue-400 hover:text-blue-300 text-sm"
                        disabled={report.status !== 'ready'}
                      >
                        <Download className="w-4 h-4" />
                        Download
                      </button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </PageWrapper>
  );
}

export default Reports;